name: Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy-to-gcp:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: SSH to GCP VM and execute command
      id: compute-ssh
      uses: google-github-actions/ssh-compute@v1
      with:
        project_id : '${{ secrets.GCP_PROJECT_ID }}'
        instance_name: 'instance-20241119-090819'
        zone: 'europe-west1-b'
        ssh_private_key: '${{ secrets.GCP_SSH_PRIVATE_KEY }}'
        command: 'echo Hello world'


   # - name: Set up Docker
   #   uses: docker/setup-buildx-action@v2

  #  - name: Build Docker Images
 #     run: |
# echo "${{secrets.gcp_credentials }}" > service-account.json
# docker build -t 2024_kubernetes_post_pusher -f ./post_pusher/Dockerfile .
# docker build -t 2024_kubernetes_post_consumer -f ./post_consumer/Dockerfile .

#    - name: SSH into GCP VM and Deploy
 #     uses: google-github-actions/ssh-compute@v1
  #    with:
  #      instance_name: 'instance-20241119-090819'
   #     zone: 'europe-west1-b'
    #    ssh_private_key: '${{ secrets.GCP_SSH_PRIVATE_KEY }}'
     #   command: |
      #    echo "Deploying on GCP VM..."
# docker run 2024_kubernetes_post_pusher
# docker run 2024_kubernetes_post_consumer
