name: Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy-to-gcp:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.gcp_credentials }}'

    - name: Add SSH Public Key to GCP VM
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > ~/.ssh/private_key
        chmod 600 ~/.ssh/private_key
        echo "${{ secrets.GCP_SSH_PUBLIC_KEY }}" > ~/.ssh/private_key.pub
        chmod 644 ~/.ssh/private_key.pub
        gcloud compute ssh --zone "europe-west1-b" "instance-20241119-090819" --project "${{ secrets.GCP_PROJECT_ID }}" \
        --command "echo Hello world" --quiet


   # - name: Set up Docker
   #   uses: docker/setup-buildx-action@v2

  #  - name: Build Docker Images
 #     run: |
# echo "${{secrets.gcp_credentials }}" > service-account.json
# docker build -t 2024_kubernetes_post_pusher -f ./post_pusher/Dockerfile .
# docker build -t 2024_kubernetes_post_consumer -f ./post_consumer/Dockerfile .

#    - name: SSH into GCP VM and Deploy
 #     uses: google-github-actions/ssh-compute@v1
  #    with:
  #      instance_name: 'instance-20241119-090819'
   #     zone: 'europe-west1-b'
    #    ssh_private_key: '${{ secrets.GCP_SSH_PRIVATE_KEY }}'
     #   command: |
      #    echo "Deploying on GCP VM..."
# docker run 2024_kubernetes_post_pusher
# docker run 2024_kubernetes_post_consumer
