name: Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Authenticate to GCP
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.gcp_credentials }}'

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Images
      run: |
        echo "${{secrets.gcp_credentials }}" > service-account.json
        docker build -t 2024_kubernetes_post_pusher -f ./post_pusher/Dockerfile .
        docker build -t 2024_kubernetes_post_consumer -f ./post_consumer/Dockerfile .

    - name: Push Docker Images to GCP Artifact Registry
      run: |
        docker tag 2024_kubernetes_post_pusher gcr.io/${{ secrets.GCP_PROJECT_ID }}/2024_kubernetes_post_pusher
        docker tag 2024_kubernetes_post_consumer gcr.io/${{ secrets.GCP_PROJECT_ID }}/2024_kubernetes_post_consumer
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/2024_kubernetes_post_pusher
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/2024_kubernetes_post_consumer

    - name: SSH into GCP VM and Deploy
      uses: google-github-actions/ssh-compute@v1
      with:
        instance_name: 'instance-20241119-090819'
        zone: 'europe-west1-b'
        ssh_private_key: '${{ secrets.GCP_SSH_PRIVATE_KEY }}'
        command: |
          echo "Deploying on GCP VM..."
          docker pull gcr.io/${{ secrets.GCP_PROJECT_ID }}/2024_kubernetes_post_pusher
          docker pull gcr.io/${{ secrets.GCP_PROJECT_ID }}/2024_kubernetes_post_consumer
          docker run --rm -d gcr.io/${{ secrets.GCP_PROJECT_ID }}/2024_kubernetes_post_pusher
          docker run --rm -d gcr.io/${{ secrets.GCP_PROJECT_ID }}/2024_kubernetes_post_consumer
